# Generated by Django 3.2.13 on 2022-07-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomePessoa', models.CharField(max_length=100)),
                ('telefonePessoa', models.CharField(max_length=100)),
                ('cpfPessoa', models.IntegerField()),
                ('dataNascimento', models.DateField()),
                ('senhaPessoa', models.CharField(max_length=100)),
            ],
        ),
    ]
