# Generated by Django 4.0.6 on 2022-07-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifood_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('complemento', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('cep', models.IntegerField()),
            ],
        ),
    ]
